(c-declare "
#include <signal.h>
typedef void (*SIGNAL_HANDLER)(int);
")

(c-define (raise-signal-exception sig)
          (int)
          void
          "raise_signal_exception" ""
  (raise (cons 'signal-exception sig)))

(define (signal-exception? e)
  (and (pair? e) (eq? 'signal-exception (car e))))

(c-declare "
static void signal_handler(int x) {
    raise_signal_exception(x);
}")

(define signal-set-exception!
  (c-lambda (int) void "signal(___arg1, signal_handler);"))

(define signal-set-ignore!
  (c-lambda (int) void "signal(___arg1, SIG_IGN);"))

(define signal-set-default!
  (c-lambda (int) void "signal(___arg1, SIG_DFL);"))

(define send-signal
  (c-lambda (unsigned-int int)
    int "___result = kill(___arg1, ___arg2);"))

(define signal-SIGHUP-code (c-lambda () int "___result = SIGHUP;"))
(define signal-SIGINT-code (c-lambda () int "___result = SIGINT;"))
(define signal-SIGQUIT-code (c-lambda () int "___result = SIGQUIT;"))
(define signal-SIGILL-code (c-lambda () int "___result = SIGILL;"))
(define signal-SIGTRAP-code (c-lambda () int "___result = SIGTRAP;"))
(define signal-SIGABRT-code (c-lambda () int "___result = SIGABRT;"))
(define signal-SIGBUS-code (c-lambda () int "___result = SIGBUS;"))
(define signal-SIGFPE-code (c-lambda () int "___result = SIGFPE;"))
(define signal-SIGKILL-code (c-lambda () int "___result = SIGKILL;"))
(define signal-SIGUSR1-code (c-lambda () int "___result = SIGUSR1;"))
(define signal-SIGSEGV-code (c-lambda () int "___result = SIGSEGV;"))
(define signal-SIGUSR2-code (c-lambda () int "___result = SIGUSR2;"))
(define signal-SIGPIPE-code (c-lambda () int "___result = SIGPIPE;"))
(define signal-SIGALRM-code (c-lambda () int "___result = SIGALRM;"))
(define signal-SIGTERM-code (c-lambda () int "___result = SIGTERM;"))
(define signal-SIGSTKFLT-code (c-lambda () int "___result = SIGSTKFLT;"))
(define signal-SIGCHLD-code (c-lambda () int "___result = SIGCHLD;"))
(define signal-SIGCONT-code (c-lambda () int "___result = SIGCONT;"))
(define signal-SIGSTOP-code (c-lambda () int "___result = SIGSTOP;"))
(define signal-SIGTSTP-code (c-lambda () int "___result = SIGTSTP;"))
(define signal-SIGTTIN-code (c-lambda () int "___result = SIGTTIN;"))
(define signal-SIGTTOU-code (c-lambda () int "___result = SIGTTOU;"))
(define signal-SIGURG-code (c-lambda () int "___result = SIGURG;"))
(define signal-SIGXCPU-code (c-lambda () int "___result = SIGXCPU;"))
(define signal-SIGXFSZ-code (c-lambda () int "___result = SIGXFSZ;"))
(define signal-SIGVTALRM-code (c-lambda () int "___result = SIGVTALRM;"))
(define signal-SIGPROF-code (c-lambda () int "___result = SIGPROF;"))
(define signal-SIGWINCH-code (c-lambda () int "___result = SIGWINCH;"))
(define signal-SIGIO-code (c-lambda () int "___result = SIGIO;"))
(define signal-SIGPWR-code (c-lambda () int "___result = SIGPWR;"))
(define signal-SIGSYS-code (c-lambda () int "___result = SIGSYS;"))
(define signal-SIGRTMIN-code (c-lambda () int "___result = SIGRTMIN;"))
(define signal-SIGRTMIN+1-code (c-lambda () int "___result = SIGRTMIN+1;"))
(define signal-SIGRTMIN+2-code (c-lambda () int "___result = SIGRTMIN+2;"))
(define signal-SIGRTMIN+3-code (c-lambda () int "___result = SIGRTMIN+3;"))
(define signal-SIGRTMIN+4-code (c-lambda () int "___result = SIGRTMIN+4;"))
(define signal-SIGRTMIN+5-code (c-lambda () int "___result = SIGRTMIN+5;"))
(define signal-SIGRTMIN+6-code (c-lambda () int "___result = SIGRTMIN+6;"))
(define signal-SIGRTMIN+7-code (c-lambda () int "___result = SIGRTMIN+7;"))
(define signal-SIGRTMIN+8-code (c-lambda () int "___result = SIGRTMIN+8;"))
(define signal-SIGRTMIN+9-code (c-lambda () int "___result = SIGRTMIN+9;"))
(define signal-SIGRTMIN+10-code (c-lambda () int "___result = SIGRTMIN+10;"))
(define signal-SIGRTMIN+11-code (c-lambda () int "___result = SIGRTMIN+11;"))
(define signal-SIGRTMIN+12-code (c-lambda () int "___result = SIGRTMIN+12;"))
(define signal-SIGRTMIN+13-code (c-lambda () int "___result = SIGRTMIN+13;"))
(define signal-SIGRTMIN+14-code (c-lambda () int "___result = SIGRTMIN+14;"))
(define signal-SIGRTMIN+15-code (c-lambda () int "___result = SIGRTMIN+15;"))
(define signal-SIGRTMAX-14-code (c-lambda () int "___result = SIGRTMAX-14;"))
(define signal-SIGRTMAX-13-code (c-lambda () int "___result = SIGRTMAX-13;"))
(define signal-SIGRTMAX-12-code (c-lambda () int "___result = SIGRTMAX-12;"))
(define signal-SIGRTMAX-11-code (c-lambda () int "___result = SIGRTMAX-11;"))
(define signal-SIGRTMAX-10-code (c-lambda () int "___result = SIGRTMAX-10;"))
(define signal-SIGRTMAX-9-code (c-lambda () int "___result = SIGRTMAX-9;"))
(define signal-SIGRTMAX-8-code (c-lambda () int "___result = SIGRTMAX-8;"))
(define signal-SIGRTMAX-7-code (c-lambda () int "___result = SIGRTMAX-7;"))
(define signal-SIGRTMAX-6-code (c-lambda () int "___result = SIGRTMAX-6;"))
(define signal-SIGRTMAX-5-code (c-lambda () int "___result = SIGRTMAX-5;"))
(define signal-SIGRTMAX-4-code (c-lambda () int "___result = SIGRTMAX-4;"))
(define signal-SIGRTMAX-3-code (c-lambda () int "___result = SIGRTMAX-3;"))
(define signal-SIGRTMAX-2-code (c-lambda () int "___result = SIGRTMAX-2;"))
(define signal-SIGRTMAX-1-code (c-lambda () int "___result = SIGRTMAX-1;"))
(define signal-SIGRTMAX-code (c-lambda () int "___result = SIGRTMAX;"))

(define *SIGHUP* (signal-SIGHUP-code))
(define *SIGINT* (signal-SIGINT-code))
(define *SIGQUIT* (signal-SIGQUIT-code))
(define *SIGILL* (signal-SIGILL-code))
(define *SIGTRAP* (signal-SIGTRAP-code))
(define *SIGABRT* (signal-SIGABRT-code))
(define *SIGBUS* (signal-SIGBUS-code))
(define *SIGFPE* (signal-SIGFPE-code))
(define *SIGKILL* (signal-SIGKILL-code))
(define *SIGUSR1* (signal-SIGUSR1-code))
(define *SIGSEGV* (signal-SIGSEGV-code))
(define *SIGUSR2* (signal-SIGUSR2-code))
(define *SIGPIPE* (signal-SIGPIPE-code))
(define *SIGALRM* (signal-SIGALRM-code))
(define *SIGTERM* (signal-SIGTERM-code))
(define *SIGSTKFLT* (signal-SIGSTKFLT-code))
(define *SIGCHLD* (signal-SIGCHLD-code))
(define *SIGCONT* (signal-SIGCONT-code))
(define *SIGSTOP* (signal-SIGSTOP-code))
(define *SIGTSTP* (signal-SIGTSTP-code))
(define *SIGTTIN* (signal-SIGTTIN-code))
(define *SIGTTOU* (signal-SIGTTOU-code))
(define *SIGURG* (signal-SIGURG-code))
(define *SIGXCPU* (signal-SIGXCPU-code))
(define *SIGXFSZ* (signal-SIGXFSZ-code))
(define *SIGVTALRM* (signal-SIGVTALRM-code))
(define *SIGPROF* (signal-SIGPROF-code))
(define *SIGWINCH* (signal-SIGWINCH-code))
(define *SIGIO* (signal-SIGIO-code))
(define *SIGPWR* (signal-SIGPWR-code))
(define *SIGSYS* (signal-SIGSYS-code))
(define *SIGRTMIN* (signal-SIGRTMIN-code))
(define *SIGRTMIN+1* (signal-SIGRTMIN+1-code))
(define *SIGRTMIN+2* (signal-SIGRTMIN+2-code))
(define *SIGRTMIN+3* (signal-SIGRTMIN+3-code))
(define *SIGRTMIN+4* (signal-SIGRTMIN+4-code))
(define *SIGRTMIN+5* (signal-SIGRTMIN+5-code))
(define *SIGRTMIN+6* (signal-SIGRTMIN+6-code))
(define *SIGRTMIN+7* (signal-SIGRTMIN+7-code))
(define *SIGRTMIN+8* (signal-SIGRTMIN+8-code))
(define *SIGRTMIN+9* (signal-SIGRTMIN+9-code))
(define *SIGRTMIN+10* (signal-SIGRTMIN+10-code))
(define *SIGRTMIN+11* (signal-SIGRTMIN+11-code))
(define *SIGRTMIN+12* (signal-SIGRTMIN+12-code))
(define *SIGRTMIN+13* (signal-SIGRTMIN+13-code))
(define *SIGRTMIN+14* (signal-SIGRTMIN+14-code))
(define *SIGRTMIN+15* (signal-SIGRTMIN+15-code))
(define *SIGRTMAX-14* (signal-SIGRTMAX-14-code))
(define *SIGRTMAX-13* (signal-SIGRTMAX-13-code))
(define *SIGRTMAX-12* (signal-SIGRTMAX-12-code))
(define *SIGRTMAX-11* (signal-SIGRTMAX-11-code))
(define *SIGRTMAX-10* (signal-SIGRTMAX-10-code))
(define *SIGRTMAX-9* (signal-SIGRTMAX-9-code))
(define *SIGRTMAX-8* (signal-SIGRTMAX-8-code))
(define *SIGRTMAX-7* (signal-SIGRTMAX-7-code))
(define *SIGRTMAX-6* (signal-SIGRTMAX-6-code))
(define *SIGRTMAX-5* (signal-SIGRTMAX-5-code))
(define *SIGRTMAX-4* (signal-SIGRTMAX-4-code))
(define *SIGRTMAX-3* (signal-SIGRTMAX-3-code))
(define *SIGRTMAX-2* (signal-SIGRTMAX-2-code))
(define *SIGRTMAX-1* (signal-SIGRTMAX-1-code))
(define *SIGRTMAX* (signal-SIGRTMAX-code))
